---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artisans/public_html/repositories/unp-laboratorios-electronica/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH